spring:
  redis:
    password: redis      # 密码（默认为空）
    timeout: 6000  # 连接超时时长（毫秒）
    cluster:
      nodes: 10.231.38.150:6379
      max-redirects: 3 # 获取失败 最大重定向次数
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  secondaryRedis:
    cluster:
      nodes: 127.0.0.1:6379
      password: redis1234