package com.olive.people
import com.olive.drools.bean.People
import com.olive.drools.bean.Cat
dialect "java"

rule "man"
    when
        $p : People(sex == 1 && drlType == "people")
   then
        System.out.println($p.getName() + "是男孩");
end

rule "cat"
    when
        $c : Cat(sex == 1 && $c.getName().equals("金"))
    then System.out.println($c.getName() + "是公的");
end

rule "gril"
    when
        People(sex == 0) and
        Cat(sex == 0)
    then
        System.out.println("gril规则执行");
end